Project:
  ProjectName : SauceLab

Pytest:
  IsDryRun : false
  IsFailureRerun : false
  ParallelCount : 3
  IsParallelGroupFile : false
  DeleteConftest : true
  Tag : add_cart

Browser:
  IsHeadless : false
  DefaultBrowser : chromium
  IsMultiBrowser : false
  DeleteDownloads : true
  MultiBrowserList : 
    - chromium
    - firefox
    - webkit

Allure:
  Generate : true
  AutoOpenServer : false

URL:
  SauceLab : https://saucedemo.com
  SelDev : https://www.selenium.dev/downloads/

Credentials:
  UserName : standard_user
  Password : secret_sauce

